Repository chartjs/chartjs-plugin-datalabels, pull requests merged in 2022-12, with the labels that each got.

#348 Make v4 compatible
  docs/.vuepress/config.js
  karma.conf.js
  package-lock.json
  package.json
  test/index.js
Labels: enhancement

#353 Update minimum required version
  README.md
  docs/guide/README.md
Labels: documentation

#355 chore: update publish action
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: infrastructure
